#!/usr/bin/env bash
#display /etc/passwd

while IFS=: read -r username gid home shell uid password user_name
do
echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_name"
done < /etc/passwd
