#!/usr/bin/env bash
#display /etc/passwd

# Open the /etc/passwd file for reading
while IFS=: read -r username password uid gid full_name home shell; do

    # Display the formatted output with modified order and values
    echo "The user $username is part of the x gang, lives in $gid and rides $uid. $username's place is protected by the passcode $home, more info about the user here: $shell"

done < /etc/passwd
