#!/usr/bin/env bash
# parse apache log

log_file="apache-access.log"

# Check if the log file exists
if [[ ! -f "$log_file" ]]; then
  echo "Log file not found: $log_file"
  exit 1
fi

# the IP address and HTTP status codes
awk '{print $1, $9}' "$log_file" 
