#!/usr/bin/env bash
#displaying the time
hour=0

while [ $hour -le 12 ]
do
minute=1
echo "Hour: $hour"

while [ $minute -lt 60 ]
do
echo "$minute"
minute=$((minute + 1))
done

hour=$((hour + 1))
done
