#!/usr/bin/env bash
# display files

if [ -e "school" ]; then
echo "school file exists"
else
echo "school file does not exist"
fi

if [ ! -s "school" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi

if [ -f "school" ]; then
echo "school file is a regular file"
else 
echo ""
fi
