#!/usr/bin/env bash
# display files

file="school"
if [ -e $file ]; then
	echo "school file exists"
	if [ -f $file ]; then
		if [ "$(wc -l < "$file")" -eq 0 ]; then
	       		echo "school file is empty"
		else
			echo "school file is not empty"
		fi
		echo "school is a regular file"
	fi

	if [ -d $file ]; then
		cd $file
		if [ "$(ls | wc -l)" -eq 0 ]; then
			echo "school file is empty"
                else
                        echo "school file is not empty"
		fi
		cd ..
	fi
else
	echo "school file does not exist"
fi
