#!/usr/bin/env bash
# Manage the manage_my_process script

PID_FILE="/var/run/my_process.pid"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch $PID_FILE
    echo "$!" > $PID_FILE
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat $PID_FILE)"
    rm $PID_FILE
elif [ "${1}" == "restart" ]
then
    kill "$(cat $PID_FILE)"
    rm $PID_FILE
    ./manage_my_process &
    touch $PID_FILE
    echo "$!" > $PID_FILE
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

