#!/usr/bin/env bash
# dislpay bash PID easily

for PID in /proc/[0-9]*; do

	PID=$(basename "$PID")

	if grep -q "bash" "/proc/"$PID""comm" 2>/dev/null; then
		echo "$PID $(cat /proc/"$PID"/comm)"
	fi
done

