#!/usr/bin/env bash
# stop without using kill or killall

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
        kill -SIGTERM "$pid"
else
        echo "'4-to_infinity_and_beyond' process is not found"
fi

