#!/usr/bin/env bash
# stop without using kill or killall

pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
        kill -SIGTERM "$pid"
else
        echo "'7-highlander' process is not found"
fi

